### ISSUE TITLE
Where is cncnet-server.exe?

### ISSUE THREAD

**Issue by peylight** [CnCNet/cncnet-tunnel#2]
Hello
In [this topic](https://forums.cncnet.org/topic/6325-how-to-host-a-cncnet-server/) there are two binary host a CnCNet server.
One of this is cncnet-server.exe. 
I want to know where is the source code of  cncnet-server.exe

**Comment by FunkyFr3sh** [comment]
It's here now: https://github.com/CnCNet/cncnet-server
